

GET http://localhost:3000/products/10
###
GET http://localhost:3000/products?page=3
####
GET http://localhost:3000/products/new
####
POST  http://localhost:3000/products
Content-Type: application/json

{
    
    "name":"Elvin",
    "second":"Zamora",
    "age":42
}